language: node_js

node_js:
  - 10.5.0
dist: trusty
services:
  - postgresql
addons:
  chrome: stable
before_script:
  - npm install nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - psql -c 'drop database if exists travis;' -U postgres
  - psql -c 'create database travis;' -U postgres

script:
  - nyc --reporter=lcov --reporter=text-lcov npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: true

after_success: 'npm run coverage'
after_fail: 'npm run coverage'
