language: node_js

node_js:
  - 10.5.0
dist: trusty
services:
  - postgresql
addons:
  chrome: stable
before_script:
  - npm install -g sequelize-cli
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - psql -c 'drop database if exists elven_ah_test;' -U postgres
  - psql -c 'create database elven_ah_test;' -U postgres
  - sequelize db:migrate --env test

script:
  - npm run test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: true

after_success: npm run coverage
